package com.smarttransport.service;

import com.smarttransport.exception.UnsupportedOperation;
import com.smarttransport.exception.VehicleNotFound;
import com.smarttransport.exception.VehicleUnderMaintenance;
import com.smarttransport.interfaces.Maintainable;
import com.smarttransport.model.Passenger;
import com.smarttransport.model.Vehicle;

import java.util.HashMap;
import java.util.Map;

public class VehicleService {
    Map<String, Vehicle> vehicleMap = new HashMap<>();

    public void addVehicle(Vehicle vehicle){
        vehicleMap.put(vehicle.getVehicleId().toUpperCase(), vehicle);
        System.out.println(vehicle.getClass().getSimpleName() + " added with ID: " + vehicle.getVehicleId());
    }

    public Vehicle searchVehicleById(String id){
        Vehicle v = vehicleMap.get(id.toUpperCase());
        if(v == null){
            throw new VehicleNotFound("Vehicle with id: " + id + " not found");
        }
        return v;
    }

    public void displayAllVehicle(){
        if(vehicleMap.isEmpty()){
            System.out.println("No Vehicle yet");
            return;
        }

        for(Vehicle v : vehicleMap.values()){
            System.out.println("ID: " + v.getVehicleId() +
                    " | Type: " + v.getClass().getSimpleName() +
                    " | Vehicle Number: " + v.getVehicleNumber() +
                    " | Driver Name: " + v.getDriverName() +
                    " | Capacity: " + v.getCapacity()
            );
        }
    }

    public void displayVehicleWithHighestRevenue(){
        if(vehicleMap.isEmpty()){
            System.out.println("No vehicle available");
            return;
        }
        Vehicle mostRevenueGeneratedVehicle = null;
        for(Vehicle vehicle : vehicleMap.values()){
            if(mostRevenueGeneratedVehicle == null || mostRevenueGeneratedVehicle.getTotalRevenue() < vehicle.getTotalRevenue()){
                mostRevenueGeneratedVehicle = vehicle;
            }
        }

        System.out.println("\n--- MAXIMUM REVENUE REPORT ---");
        if (mostRevenueGeneratedVehicle.getTotalRevenue() == 0) {
            System.out.println("No revenue generated by any vehicle.");
        } else {
            System.out.println("Vehicle ID          : " + mostRevenueGeneratedVehicle.getVehicleId());
            System.out.println("Type                : " + mostRevenueGeneratedVehicle.getClass().getSimpleName());
            System.out.println("Driver Name         : " + mostRevenueGeneratedVehicle.getDriverName());
            System.out.println("Generated Revenue   : " + mostRevenueGeneratedVehicle.getTotalRevenue());
            System.out.println("Passenger Boarded   : " + mostRevenueGeneratedVehicle.getCurrPassengerList().size());
            System.out.println("Max Limit           : " + mostRevenueGeneratedVehicle.getCapacity() + " passengers");
        }
        System.out.println("------------------------------------");
    }


    public void sendVehicleToMaintenance(String vehicleId) throws VehicleNotFound {
        Vehicle vehicle = searchVehicleById(vehicleId);

        if(vehicle instanceof Maintainable){
            Maintainable maintainableVehicle = (Maintainable) vehicle;

            if(maintainableVehicle.isUnderMaintenance()){
                System.out.println("Notice: Vehicle " + vehicleId + " is already in maintenance.");
                return;
            }

            maintainableVehicle.sendToMaintenance();
            System.out.println("Successfully sent to the maintenance");
        }else{
            throw new UnsupportedOperation("Error: " + vehicle.getClass().getSimpleName() + " does not support the maintenance");

        }
    }


    public void takeVehicleFromMaintenance(String vehicleId) throws VehicleUnderMaintenance {
        Vehicle vehicle = searchVehicleById(vehicleId);

        if(vehicle instanceof Maintainable){
            Maintainable maintainableVehicle = (Maintainable) vehicle;

            if(!maintainableVehicle.isUnderMaintenance()){
                System.out.println("Notice: Vehicle " + vehicleId + " is not in maintenance.");
                return;
            }

            maintainableVehicle.takeFromMaintenance();
            System.out.println("Successfully taken from the maintenance");
        }else{
            throw new UnsupportedOperation("Error: " + vehicle.getClass().getSimpleName() + " does not support the maintenance");
        }
    }

}
